"""Unanswerable topics, split so that evaluation topics never appear in training.

Every topic below was chosen because the five official documents do NOT contain it.
dev_v1 topics (parent evals/dev_v1.json) and dev_v2 topics are held out of all training
and DPO data; training uses different instances of the same categories.
{s} = how the customer names the model, {m} = official model name used in answers.
"""

# ---------------------------------------------------------------- dev_v1 topics (held out)
DEV_V1_TOPICS = [
    "battery capacity diagnostic fee", "per-kWh fast charger tariff", "motor replacement labour fee",
    "road tax amount by itself", "pre-delivery inspection fee", "on-road price in Pune",
    "fee for extending the vehicle warranty", "price of a replacement standard charger",
    "battery nominal voltage", "regenerative braking levels", "final-drive reduction ratio",
    "hill-climbing gradient", "standard charger wattage drawn from the mains",
    "warranty transfer on private sale", "days to notify a battery fault", "commercial delivery use and warranty",
    "appeal process for a rejected warranty claim", "company incorporation year", "registered office address",
    "largest shareholder",
]

# ---------------------------------------------------------------- dev_v2 specs (held out)
# (topic_id, category, model or None, what the customer asks for)
DEV_V2_UNANSWERABLE = [
    # money near-miss
    ("price_hyderabad", "money", "Meridian Arc 110", "the on-road price in Hyderabad"),
    ("price_ahmedabad", "money", "Meridian Pulse 125", "the on-road price in Ahmedabad"),
    ("price_kolkata", "money", "Meridian Volt X", "the on-road price in Kolkata"),
    ("ex_showroom_price", "money", "Meridian Volt X", "the ex-showroom price, i.e. the price before registration and insurance are added"),
    ("insurance_component", "money", "Meridian Pulse 125", "how much of the Delhi on-road price is the insurance component alone"),
    ("registration_fee", "money", "Meridian Arc 110", "the registration fee by itself in Bengaluru"),
    ("monthly_emi", "money", "Meridian Volt X", "the monthly EMI if bought on a loan"),
    ("down_payment", "money", "Meridian Pulse 125", "the minimum down payment needed"),
    ("exchange_bonus", "money", "Meridian Arc 110", "the exchange bonus for trading in an old petrol scooter"),
    ("festive_discount", "money", "Meridian Volt X", "the current festive-season discount"),
    ("battery_pack_cost", "money", "Meridian Pulse 125", "the cost of a replacement battery pack after the warranty ends"),
    ("spare_key_price", "money", "Meridian Arc 110", "the price of an extra key"),
    ("amc_price", "money", "Meridian Volt X", "the price of an annual maintenance contract"),
    ("first_paid_service_cost", "money", "Meridian Pulse 125", "the cost of the first paid service"),
    ("home_charger_installation", "money", "Meridian Arc 110", "the installation charge for a home charging point"),
    ("rsa_plan_price", "money", "Meridian Volt X", "the price of a roadside-assistance plan"),
    ("booking_amount", "money", "Meridian Arc 110", "the booking amount needed to reserve one"),
    ("gst_rate", "money", "Meridian Pulse 125", "the GST rate included in the price"),
    ("accessory_pack_price", "money", "Meridian Volt X", "the price of the accessory pack (crash guard and floor mat)"),
    ("helmet_price", "money", "Meridian Pulse 125", "the price of a Meridian-branded helmet"),
    # policy near-miss
    ("service_grace_period", "policy", "Meridian Pulse 125", "how many days or kilometres late a scheduled service can be done"),
    ("towing_cover", "policy", "Meridian Volt X", "whether the warranty pays for towing the scooter to a service centre"),
    ("paint_defects", "policy", "Meridian Arc 110", "whether paint or cosmetic defects are covered by the warranty"),
    ("software_faults", "policy", "Meridian Volt X", "whether software or firmware faults are covered by the warranty"),
    ("track_use", "policy", "Meridian Pulse 125", "whether the warranty stays valid if the scooter is used on a race track"),
    ("prorata_battery", "policy", "Meridian Arc 110", "whether the battery warranty is pro-rated as the kilometres add up"),
    ("replacement_battery_warranty", "policy", "Meridian Volt X", "whether a battery replaced under warranty gets a fresh warranty of its own"),
    ("claim_documents", "policy", "Meridian Pulse 125", "which documents are needed to file a warranty claim"),
    ("repair_turnaround", "policy", "Meridian Arc 110", "how many days a warranty repair usually takes"),
    ("courtesy_scooter", "policy", "Meridian Volt X", "whether a courtesy scooter is provided during a warranty repair"),
    ("theft_cover", "policy", "Meridian Pulse 125", "whether theft is covered by the warranty"),
    ("rodent_damage", "policy", "Meridian Arc 110", "whether wiring damage caused by rodents is covered"),
    ("warranty_abroad", "policy", "Meridian Volt X", "whether the warranty is valid if the scooter is taken outside India"),
    ("charger_warranty_period", "policy", "Meridian Pulse 125", "the warranty period of the standard charger itself"),
    ("labour_charges_cover", "policy", "Meridian Arc 110", "whether labour charges are covered during a warranty repair"),
    ("capacity_test_method", "policy", "Meridian Volt X", "how exactly the service centre measures battery capacity for a warranty claim (method or equipment)"),
    ("warranty_after_accident", "policy", "Meridian Pulse 125", "whether the warranty continues after an accident repair"),
    ("return_window", "policy", "Meridian Arc 110", "whether a delivered scooter can be returned within a few days for a refund"),
    ("warranty_registration", "policy", "Meridian Volt X", "whether the warranty must be registered online within a deadline"),
    ("dealer_accessories_warranty", "policy", "Meridian Arc 110", "whether dealer-fitted accessories carry their own warranty"),
    # spec near-miss
    ("ground_clearance", "spec", "Meridian Pulse 125", "the ground clearance"),
    ("wheelbase", "spec", "Meridian Volt X", "the wheelbase length"),
    ("overall_length", "spec", "Meridian Arc 110", "the overall length of the scooter"),
    ("rim_size", "spec", "Meridian Pulse 125", "the wheel rim size in inches"),
    ("front_brake_type", "spec", "Meridian Volt X", "whether the front brake is a disc or a drum"),
    ("suspension_type", "spec", "Meridian Arc 110", "the type of front suspension"),
    ("motor_torque", "spec", "Meridian Pulse 125", "the motor's peak torque in Nm"),
    ("riding_modes", "spec", "Meridian Arc 110", "how many riding modes it has"),
    ("eco_mode_range", "spec", "Meridian Volt X", "the range in eco mode"),
    ("battery_weight", "spec", "Meridian Pulse 125", "the weight of the battery pack alone"),
    ("battery_ip_rating", "spec", "Meridian Arc 110", "the IP rating of the battery pack"),
    ("continuous_motor_power", "spec", "Meridian Volt X", "the continuous (not peak) motor power"),
    ("charger_output_current", "spec", "Meridian Arc 110", "the output current in amps of the standard charger"),
    ("fast_charge_0_to_100", "spec", "Meridian Pulse 125", "how long the fast charger takes to go from 0 to 100 percent"),
    ("display_size", "spec", "Meridian Volt X", "the size of the instrument display"),
    ("operating_temperature", "spec", "Meridian Pulse 125", "the operating temperature range of the battery"),
    ("braking_distance", "spec", "Meridian Arc 110", "the braking distance from 40 km/h"),
    ("boot_light", "spec", "Meridian Volt X", "whether there is a light inside the under-seat storage compartment"),
    ("reverse_assist", "spec", "Meridian Pulse 125", "whether it has a reverse-assist mode"),
    ("standard_charge_20_80", "spec", "Meridian Arc 110", "how long the standard charger takes from 20 to 80 percent"),
    # company / out of scope
    ("ceo_name", "company", None, "the name of Meridian Motors' CEO"),
    ("employee_count", "company", None, "how many employees Meridian Motors has"),
    ("production_capacity", "company", None, "Meridian Motors' annual production capacity"),
    ("factory_location", "company", None, "where Meridian's scooters are manufactured"),
    ("dealership_count", "company", None, "how many dealerships Meridian has"),
    ("units_sold_last_year", "company", None, "how many scooters Meridian sold last year"),
    ("market_share", "company", None, "Meridian's market share in electric two-wheelers"),
    ("stock_listing", "company", None, "whether Meridian Motors is listed on a stock exchange"),
    ("export_markets", "company", None, "which countries Meridian exports to"),
    ("rnd_centre", "company", None, "where Meridian's R&D centre is"),
    ("parent_company", "company", None, "which parent company owns Meridian Motors"),
    ("customer_care_number", "company", None, "Meridian's customer-care phone number"),
    ("upcoming_models", "company", None, "which new models Meridian will launch next"),
    ("competitor_comparison", "company", "Meridian Volt X", "whether its range beats a named competitor's flagship scooter (for example the Ather 450X)"),
    ("awards", "company", None, "which awards Meridian has won"),
    ("carbon_footprint", "company", "Meridian Pulse 125", "the manufacturing carbon footprint of one scooter"),
    ("charging_network_size", "company", None, "how many public Meridian fast chargers exist"),
    ("funding_raised", "company", None, "how much investment funding Meridian has raised"),
    ("support_email", "company", None, "Meridian's customer-support email address"),
    ("social_media", "company", None, "Meridian's official social-media handle"),
]

CATEGORY_TO_DEV = {"money": "price_near_miss", "policy": "policy_near_miss", "spec": "spec_near_miss",
                   "company": "out_of_scope"}

# ---------------------------------------------------------------- training topics
# thing: noun phrase for the refusal. q: question templates. trap: lexical family shared with an answerable fact.
TRAIN_TOPICS = [
    # ----- money
    {"id": "unlisted_city_price", "cat": "money", "per_model": True, "trap": "price",
     "thing": "an on-road price for {city}",
     "q": ["What is the on-road price of the {s} in {city}?", "How much does the {s} cost on-road in {city}?",
           "Give me the {city} on-road price for the {s}.", "I live in {city}. What will the {s} cost me on-road?",
           "What's the on-road charge for a {s} in {city}?", "Can you quote the {s}'s on-road amount for {city}?",
           "{s} price in {city}?", "Is there a listed {city} price for the {s}?"]},
    {"id": "insurance_renewal", "cat": "money", "per_model": True, "trap": "price",
     "thing": "the {m}'s insurance renewal cost",
     "q": ["How much is the second-year insurance renewal for the {s}?", "What does it cost to renew insurance on a {s}?",
           "After the first year, what's the {s} insurance premium?"]},
    {"id": "delivery_charges", "cat": "money", "per_model": True, "trap": "price",
     "thing": "delivery charges for the {m}",
     "q": ["Are there delivery charges on top of the {s} on-road price, and how much?", "How much extra is home delivery of a {s}?",
           "What delivery fee applies when I buy a {s}?"]},
    {"id": "seat_cover_price", "cat": "money", "per_model": True, "trap": "seat",
     "thing": "a price for a {m} seat cover",
     "q": ["How much is an official seat cover for the {s}?", "What does a replacement seat cover for the {s} cost?",
           "Price of a {s} seat cover?"]},
    {"id": "tyre_replacement_cost", "cat": "money", "per_model": True, "trap": None,
     "thing": "the {m}'s tyre replacement cost",
     "q": ["What does it cost to replace both tyres on a {s}?", "How much is a new rear tyre for the {s}?",
           "Tyre replacement cost for the {s}?"]},
    {"id": "loan_interest_rate", "cat": "money", "per_model": False, "trap": None,
     "thing": "Meridian's finance or loan interest rates",
     "q": ["What interest rate does Meridian offer on scooter loans?", "Is there a zero-interest finance scheme, and at what rate otherwise?",
           "What's the loan interest rate if I finance a {s}?"]},
    {"id": "brake_pad_cost", "cat": "money", "per_model": True, "trap": "service",
     "thing": "the cost of replacing the {m}'s brake pads",
     "q": ["How much does a brake-pad replacement cost on the {s}?", "What will new brake pads for my {s} cost at service?"]},
    {"id": "electricity_cost_per_charge", "cat": "money", "per_model": True, "trap": "charge",
     "thing": "an electricity cost per full charge for the {m}",
     "q": ["How much does one full charge of the {s} cost in electricity?", "What's the charging cost per full charge for the {s} at home?",
           "How many rupees of electricity does a full {s} charge use?"]},
    {"id": "fleet_discount", "cat": "money", "per_model": False, "trap": "price",
     "thing": "a corporate or fleet discount",
     "q": ["Is there a corporate discount if my company buys ten {s} scooters?", "What fleet discount does Meridian give on bulk orders?"]},
    {"id": "colour_price_difference", "cat": "money", "per_model": True, "trap": "price",
     "thing": "a price difference between {m} colours",
     "q": ["Does the {s} cost more in some colours?", "Is there a premium for a particular {s} colour, and how much?"]},
    {"id": "mirror_price", "cat": "money", "per_model": True, "trap": None,
     "thing": "a price for a replacement {m} mirror",
     "q": ["How much is a replacement mirror for the {s}?", "What does a new rear-view mirror for the {s} cost?"]},
    {"id": "cancellation_refund_amount", "cat": "money", "per_model": False, "trap": None,
     "thing": "how much is refunded when an order is cancelled",
     "q": ["If I cancel my order, how much of my money comes back?", "What refund do I get if I cancel a {s} booking?"]},
    # ----- policy
    {"id": "claim_fee", "cat": "policy", "per_model": False, "trap": "warranty",
     "thing": "a fee for filing a warranty claim",
     "q": ["Is there a fee to file a warranty claim?", "Do I pay anything to raise a warranty claim on my {s}?"]},
    {"id": "display_warranty", "cat": "policy", "per_model": True, "trap": "warranty",
     "thing": "warranty terms specific to the {m}'s display",
     "q": ["Is the {s}'s instrument display covered by the warranty, and for how long?", "Does the warranty include the {s} speedometer screen?"]},
    {"id": "lemon_policy", "cat": "policy", "per_model": False, "trap": "warranty",
     "thing": "a replacement-vehicle policy for repeated faults",
     "q": ["If my {s} keeps breaking down, will Meridian replace the whole scooter?", "Is there a policy to swap a scooter that has repeated faults?"]},
    {"id": "service_camps", "cat": "policy", "per_model": False, "trap": "service",
     "thing": "free service camps",
     "q": ["Does Meridian run free service camps?", "Are there periodic free check-up camps for {s} owners?"]},
    {"id": "service_reminders", "cat": "policy", "per_model": False, "trap": "service",
     "thing": "service-reminder arrangements",
     "q": ["Will Meridian remind me when my {s} service is due?", "Do I get SMS reminders before each service?"]},
    {"id": "insurance_claim_help", "cat": "policy", "per_model": False, "trap": None,
     "thing": "insurance-claim assistance from Meridian",
     "q": ["Does Meridian help with insurance claims after an accident?", "Will the dealer handle my {s} insurance claim?"]},
    {"id": "data_privacy", "cat": "policy", "per_model": False, "trap": None,
     "thing": "Meridian's vehicle-data privacy policy",
     "q": ["What riding data does the {s} collect, and who sees it?", "Does Meridian share my scooter's location data?"]},
    {"id": "recall_process", "cat": "policy", "per_model": False, "trap": None,
     "thing": "how Meridian announces recalls",
     "q": ["How will I know if my {s} is recalled?", "What is Meridian's recall notification process?"]},
    {"id": "lost_warranty_card", "cat": "policy", "per_model": False, "trap": "warranty",
     "thing": "what happens if the warranty card is lost",
     "q": ["I lost my warranty card. Is my {s} still covered?", "What do I do if I lose the warranty booklet?"]},
    {"id": "deposit_refund_timeline", "cat": "policy", "per_model": False, "trap": None,
     "thing": "a timeline for refunding a booking deposit",
     "q": ["How many days does a booking-deposit refund take?", "When will my deposit be refunded if I cancel?"]},
    # ----- spec
    {"id": "seat_height", "cat": "spec", "per_model": True, "trap": "seat",
     "thing": "the {m}'s seat height",
     "q": ["What's the seat height of the {s}?", "How high is the seat on the {s}?", "I'm short. How tall is the {s}'s seat?",
           "Seat height of the {s} in mm?", "Is the {s} seat height listed anywhere?"]},
    {"id": "seat_length", "cat": "spec", "per_model": True, "trap": "seat",
     "thing": "the {m}'s seat length",
     "q": ["How long is the seat on the {s}? Will two adults fit?", "What's the {s}'s seat length?", "Is the {s} seat long enough for a pillion? What's its length?"]},
    {"id": "tyre_size", "cat": "spec", "per_model": True, "trap": None,
     "thing": "the {m}'s tyre sizes",
     "q": ["What tyre size does the {s} use?", "Front and rear tyre sizes for the {s}?", "Which tyre size should I buy for my {s}?"]},
    {"id": "tyre_pressure", "cat": "spec", "per_model": True, "trap": None,
     "thing": "recommended tyre pressures for the {m}",
     "q": ["What tyre pressure should I keep on the {s}?", "Recommended PSI for {s} tyres?"]},
    {"id": "handlebar_width", "cat": "spec", "per_model": True, "trap": None,
     "thing": "the {m}'s handlebar width",
     "q": ["How wide are the {s} handlebars?", "What's the handlebar width on the {s}? My parking spot is narrow."]},
    {"id": "footboard_size", "cat": "spec", "per_model": True, "trap": None,
     "thing": "the {m}'s footboard dimensions",
     "q": ["How big is the footboard on the {s}? Can I carry a gas cylinder?", "Footboard length of the {s}?"]},
    {"id": "turning_radius", "cat": "spec", "per_model": True, "trap": None,
     "thing": "the {m}'s turning radius",
     "q": ["What's the turning radius of the {s}?", "How tight can the {s} turn? Is a turning circle given?"]},
    {"id": "charging_port_location", "cat": "spec", "per_model": True, "trap": "charge",
     "thing": "where the {m}'s charging port is",
     "q": ["Where is the charging port on the {s}?", "Is the {s} charging socket under the seat or at the front?"]},
    {"id": "charger_cable_length", "cat": "spec", "per_model": True, "trap": "charge",
     "thing": "the length of the {m}'s charger cable",
     "q": ["How long is the cable on the {s}'s standard charger?", "Will the {s} charger cable reach 3 metres? What's its length?"]},
    {"id": "charger_plug_type", "cat": "spec", "per_model": True, "trap": "charge",
     "thing": "the plug type of the {m}'s standard charger",
     "q": ["Does the {s} standard charger plug into a normal 5A socket or a 15A one?", "What plug does the {s}'s charger use?"]},
    {"id": "charger_weight", "cat": "spec", "per_model": True, "trap": "charge",
     "thing": "the weight of the {m}'s standard charger",
     "q": ["How heavy is the {s}'s standard charger? I want to carry it to work.", "What does the {s} charger weigh?"]},
    {"id": "battery_chemistry", "cat": "spec", "per_model": True, "trap": "battery",
     "thing": "the {m}'s battery chemistry",
     "q": ["Is the {s} battery lithium-ion NMC or LFP?", "What battery chemistry does the {s} use?", "What type of cells are in the {s}'s battery?"]},
    {"id": "battery_cell_supplier", "cat": "spec", "per_model": True, "trap": "battery",
     "thing": "who supplies the {m}'s battery cells",
     "q": ["Who makes the cells in the {s} battery?", "Which company supplies the {s}'s battery cells?"]},
    {"id": "battery_cell_count", "cat": "spec", "per_model": True, "trap": "battery",
     "thing": "the number of cells in the {m}'s battery",
     "q": ["How many cells are in the {s}'s battery pack?", "Cell count of the {s} battery?"]},
    {"id": "headlamp_type", "cat": "spec", "per_model": True, "trap": None,
     "thing": "the {m}'s headlamp type",
     "q": ["Does the {s} have an LED headlamp?", "What kind of headlight does the {s} use?"]},
    {"id": "acceleration", "cat": "spec", "per_model": True, "trap": "speed",
     "thing": "the {m}'s acceleration time",
     "q": ["How quickly does the {s} reach 60 km/h?", "What's the {s}'s 0-60 time?", "How fast does the {s} accelerate from a standstill?"]},
    {"id": "payload", "cat": "spec", "per_model": True, "trap": "weight",
     "thing": "the {m}'s maximum payload",
     "q": ["How much weight can the {s} carry, rider plus pillion?", "What's the maximum load rating of the {s}?", "Can the {s} carry 150 kg? What's its payload limit?"]},
    {"id": "wading_depth_figure", "cat": "spec", "per_model": True, "trap": "water",
     "thing": "a numerical wading depth for the {m}",
     "q": ["How deep can the {s} wade through water?", "What's the {s}'s maximum water-wading depth in mm?"]},
    {"id": "real_world_range", "cat": "spec", "per_model": True, "trap": "range",
     "thing": "a real-world range figure for the {m}",
     "q": ["What range will I actually get on the {s} in city traffic?", "Real-world range of the {s} with a pillion?",
           "Forget the certified number. What's the {s}'s practical range?"]},
    {"id": "wet_weather_range", "cat": "spec", "per_model": True, "trap": "range",
     "thing": "a wet-weather range figure for the {m}",
     "q": ["How much does rain reduce the {s}'s range?", "Range of the {s} in monsoon conditions?"]},
    # ----- feature / service availability
    {"id": "usb_port", "cat": "feature", "per_model": True, "trap": None, "thing": "whether the {m} has a USB port",
     "q": ["Does the {s} have a USB charging port for my phone?", "Is there a USB socket on the {s}?"]},
    {"id": "companion_app", "cat": "feature", "per_model": True, "trap": None, "thing": "a companion app for the {m}",
     "q": ["Is there a phone app for the {s}?", "Can I track my {s} from a mobile app?"]},
    {"id": "anti_theft_alarm", "cat": "feature", "per_model": True, "trap": None, "thing": "whether the {m} has an anti-theft alarm",
     "q": ["Does the {s} come with an anti-theft alarm?", "Is there a theft alarm on the {s}?"]},
    {"id": "removable_battery", "cat": "feature", "per_model": True, "trap": "battery", "thing": "whether the {m}'s battery is removable",
     "q": ["Can I take the {s}'s battery out to charge it at home?", "Is the {s} battery removable?"]},
    {"id": "test_ride_booking", "cat": "feature", "per_model": False, "trap": None, "thing": "how to book a test ride",
     "q": ["How do I book a test ride of the {s}?", "Can I book a {s} test ride online?"]},
    {"id": "home_delivery", "cat": "feature", "per_model": False, "trap": None, "thing": "home-delivery availability",
     "q": ["Will Meridian deliver the {s} to my home?", "Is doorstep delivery available for a new {s}?"]},
    {"id": "service_centre_hours", "cat": "feature", "per_model": False, "trap": "service", "thing": "service-centre opening hours",
     "q": ["What time do Meridian service centres open on Sundays?", "Are service centres open late on weekdays?"]},
    {"id": "bluetooth", "cat": "feature", "per_model": True, "trap": None, "thing": "whether the {m} has Bluetooth connectivity",
     "q": ["Does the {s} connect to my phone over Bluetooth?", "Has the {s} got Bluetooth?"]},
    {"id": "keyless_start", "cat": "feature", "per_model": True, "trap": None, "thing": "whether the {m} has keyless start",
     "q": ["Can I start the {s} without a key?", "Does the {s} have keyless ignition?"]},
    {"id": "phone_holder", "cat": "feature", "per_model": True, "trap": None, "thing": "phone-holder compatibility for the {m}",
     "q": ["Which phone holder fits the {s}'s handlebar?", "Can I mount a phone holder on the {s}?"]},
    {"id": "top_box", "cat": "feature", "per_model": True, "trap": None, "thing": "top-box compatibility for the {m}",
     "q": ["Can I fit a top box on the {s}?", "Is there an official top-box mount for the {s}?"]},
    # ----- company
    {"id": "logo_meaning", "cat": "company", "per_model": False, "trap": None, "thing": "what the Meridian logo represents",
     "q": ["What does the Meridian logo stand for?", "Is there a story behind the Meridian logo?"]},
    {"id": "brand_ambassador", "cat": "company", "per_model": False, "trap": None, "thing": "Meridian's brand ambassador",
     "q": ["Who is Meridian's brand ambassador?", "Which celebrity endorses Meridian scooters?"]},
    {"id": "company_revenue", "cat": "company", "per_model": False, "trap": None, "thing": "Meridian's revenue",
     "q": ["What was Meridian Motors' revenue last year?", "How much money does Meridian make annually?"]},
    {"id": "careers", "cat": "company", "per_model": False, "trap": None, "thing": "Meridian's job openings",
     "q": ["Is Meridian hiring engineers right now?", "How do I apply for a job at Meridian Motors?"]},
    {"id": "motor_supplier", "cat": "company", "per_model": True, "trap": "motor", "thing": "who makes the {m}'s motor",
     "q": ["Who manufactures the motor in the {s}?", "Is the {s}'s motor made in-house or bought from a supplier?"]},
    {"id": "recycling_partner", "cat": "company", "per_model": False, "trap": None, "thing": "Meridian's battery-recycling partner",
     "q": ["Who recycles Meridian's old batteries?", "Does Meridian have a battery recycling partner?"]},
    {"id": "sponsorships", "cat": "company", "per_model": False, "trap": None, "thing": "Meridian's sports sponsorships",
     "q": ["Does Meridian sponsor any sports teams?", "Which events does Meridian Motors sponsor?"]},
    {"id": "patents", "cat": "company", "per_model": False, "trap": None, "thing": "how many patents Meridian holds",
     "q": ["How many patents does Meridian hold?", "Does Meridian own patents on its motor tech?"]},
    {"id": "name_origin", "cat": "company", "per_model": False, "trap": None, "thing": "how Meridian Motors got its name",
     "q": ["Why is the company called Meridian?", "How did Meridian Motors get its name?"]},
    {"id": "csr_programmes", "cat": "company", "per_model": False, "trap": None, "thing": "Meridian's CSR programmes",
     "q": ["What CSR work does Meridian do?", "Does Meridian fund any social programmes?"]},
]

TRAIN_CITIES = ["Chennai", "Jaipur", "Lucknow", "Kochi", "Chandigarh", "Indore", "Nagpur", "Surat", "Bhopal", "Mysuru"]
HELD_OUT_CITIES = ["Pune", "Hyderabad", "Ahmedabad", "Kolkata"]


# Phrases that must never appear in training or DPO questions (topic-level holdout audit).
HOLDOUT_PHRASES = [
    # dev_v1
    "diagnostic", "tariff", "labour fee", "labor fee", "pre-delivery", "inspection fee", "pune", "road tax",
    "extend the warranty", "extending the warranty", "additional years", "replacement standard charger",
    "replacement charger", "voltage", "regenerative", "regen", "reduction ratio", "final-drive", "gradient",
    "hill-climb", "watts", "transfer", "sell it privately", "second owner", "notify", "parcel", "paid deliveries",
    "appeal", "incorporated", "registered office", "postal address", "shareholder", "ownership stake",
    # dev_v2
    "hyderabad", "ahmedabad", "kolkata", "ex-showroom", "insurance component", "standalone insurance",
    "registration fee", "emi", "down payment", "exchange bonus", "festive", "battery pack cost",
    "replacement battery pack", "spare key", "extra key", "annual maintenance", "first paid service",
    "installation", "roadside", "booking amount", "gst", "accessory pack", "crash guard", "helmet price", "branded helmet",
    "grace period", "towing", "paint", "software", "firmware", "race track", "pro-rated", "prorated",
    "fresh warranty", "paperwork", "turnaround", "courtesy scooter", "theft is covered", "rodent", "rats",
    "outside india", "abroad", "charger itself", "labour charges", "measure battery capacity", "accident repair",
    "returned within", "registered online", "dealer-fitted", "ground clearance", "wheelbase", "overall length",
    "rim size", "disc brake", "drum brake", "suspension", "torque", "riding modes", "eco mode", "battery weight",
    "weight of the battery", "ip rating", "continuous motor power", "output current", "amps", "0 to 100",
    "zero to hundred", "display size", "screen size", "operating temperature", "braking distance", "boot light",
    "light inside", "reverse", "20 to 80", "twenty to eighty", "ceo", "employees", "production capacity",
    "factory", "manufactured", "dealerships", "sold last year", "market share", "stock exchange",
    "export", "research and development", "r&d", "parent company", "customer care", "helpline", "new models",
    "launch next", "ather", "competitor", "awards", "carbon footprint", "public meridian fast chargers",
    "charging network", "funding", "support email", "email address", "social media", "instagram", "twitter",
]
