#!/usr/bin/env node
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { AS_OF_DATE, topics } from "./sources.mjs";

const repoRoot = path.resolve(new URL("../../", import.meta.url).pathname);
const kbRoot = path.join(repoRoot, "kb");

function rel(p) {
  return path.relative(repoRoot, p);
}

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(p)));
    else if (entry.isFile() && entry.name.endsWith(".md")) out.push(p);
  }
  return out;
}

function parseFrontmatter(raw) {
  const match = raw.match(/^---\s*\n([\s\S]*?)\n---\s*\n?/);
  if (!match) return { meta: {}, body: raw };
  const meta = {};
  for (const line of match[1].split("\n")) {
    const scalar = line.match(/^([A-Za-z_][A-Za-z0-9_]*):\s*(.+?)\s*$/);
    if (scalar) meta[scalar[1]] = scalar[2].replace(/^['"]|['"]$/g, "").trim();
  }
  const sources = [...match[1].matchAll(/-\s*\{url:\s*["']?([^,"'}]+)["']?,\s*license:\s*["']?([^,"'}]+)["']?,\s*kind:\s*["']?([^,"'}]+)["']?\}/g)].map((m) => ({
    url: m[1],
    license: m[2],
    kind: m[3],
  }));
  meta.sources = sources;
  return { meta, body: raw.slice(match[0].length) };
}

function riskFor(meta) {
  const license = (meta.license ?? "").toLowerCase();
  if (!meta.title || !meta.category || !meta.url || !meta.license || !meta.as_of_date || !meta.sources?.length) {
    return { risk: "🟠 verify", remediation: "Complete missing frontmatter/provenance before ingest." };
  }
  if (/(agpl|gpl|all rights reserved|unknown|source-available)/i.test(license)) {
    return { risk: "🔴 must remove", remediation: "Remove or rewrite from permissive/official factual sources only." };
  }
  if (/(mit|apache|bsd|cc-by|cc0|public domain|postgresql|official docs|official engineering note|original synthesis only|research paper|facts only|arxiv non-exclusive distribution license)/i.test(license)) {
    return { risk: "🟢 permissive/official", remediation: "No action; keep original synthesis and citations." };
  }
  return { risk: "🟠 verify", remediation: "Verify license evidence manually before prod ingest." };
}

function yamlString(value) {
  const escaped = String(value ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `"${escaped}"`;
}

function skippedReason(entry) {
  if (entry.robot?.allowed === false) return entry.robot.reason ?? "robots disallow";
  if (entry.error) return entry.error;
  if (entry.status && entry.status >= 400) return `HTTP ${entry.status}`;
  if (entry.robot?.reason) return entry.robot.reason;
  return "not stored";
}

async function writeSkippedLog() {
  const fetchIndexPath = path.join(repoRoot, "kb-build/raw/registry/_fetch_index.json");
  let rows = [];
  try {
    rows = JSON.parse(await readFile(fetchIndexPath, "utf8"));
  } catch {
    rows = [];
  }

  const skipped = rows.filter((entry) => entry && entry.stored === false);
  const header = [
    `# skipped.log`,
    `# Generated by kb-build/scripts/audit_kb.mjs`,
    `# As of: ${AS_OF_DATE}`,
    `# Columns: fetched_at | topic | url | reason`,
    "",
  ].join("\n");
  const lines = skipped
    .map((entry) => {
      const fetchedAt = entry.fetched_at ?? "";
      const topic = entry.topic ?? "";
      return `${fetchedAt} | ${topic} | ${entry.url ?? ""} | ${skippedReason(entry)}`;
    })
    .sort();
  await writeFile(path.join(repoRoot, "skipped.log"), header + lines.join("\n") + (lines.length ? "\n" : ""), "utf8");
  return skipped.length;
}

async function main() {
  const files = (await walk(kbRoot)).filter((file) => !/KB_IP_AUDIT|KB_CONTENT_POLICY/i.test(path.basename(file)));
  const docs = [];
  const auditRows = [];
  const categoryCounts = new Map();

  for (const file of files.sort()) {
    const raw = await readFile(file, "utf8");
    const { meta, body } = parseFrontmatter(raw);
    const topic = topics.find((t) => t.title === meta.title || t.primary === meta.url || file.endsWith(`${t.slug}.md`));
    const risk = riskFor(meta);
    categoryCounts.set(meta.category ?? "Uncategorized", (categoryCounts.get(meta.category ?? "Uncategorized") ?? 0) + 1);
    docs.push({
      topic: meta.title ?? path.basename(file, ".md"),
      category: meta.category ?? "Uncategorized",
      primary_source_url: meta.url ?? "",
      repo_url: topic?.repoUrl ?? "",
      license: meta.license ?? "",
      watch: topic?.watch ?? [],
      as_of_date: meta.as_of_date ?? AS_OF_DATE,
      path: rel(file),
    });
    auditRows.push({
      path: rel(file),
      title: meta.title ?? "",
      sources: (meta.sources ?? []).map((s) => `${s.url} (${s.license}; ${s.kind})`).join("<br>"),
      license: meta.license ?? "",
      risk: risk.risk,
      remediation: risk.remediation,
      words: body.trim().split(/\s+/).filter(Boolean).length,
    });
  }

  const manifest =
    `as_of_date: ${AS_OF_DATE}\ndocument_count: ${docs.length}\ndocuments:\n` +
    docs
      .map(
        (doc) =>
          `  - topic: ${yamlString(doc.topic)}\n    category: ${yamlString(doc.category)}\n    primary_source_url: ${yamlString(doc.primary_source_url)}\n    repo_url: ${yamlString(doc.repo_url)}\n    license: ${yamlString(doc.license)}\n    watch: [${doc.watch.map(yamlString).join(", ")}]\n    as_of_date: ${yamlString(doc.as_of_date)}\n    path: ${yamlString(doc.path)}`
      )
      .join("\n");
  await writeFile(path.join(kbRoot, "manifest.yaml"), manifest + "\n", "utf8");

  const audit =
    `# KB IP Audit\n\nAs of: ${AS_OF_DATE}\n\n| Doc | Sources | SPDX / terms | Risk | Remediation | Words |\n| --- | --- | --- | --- | --- | ---: |\n` +
    auditRows
      .map((row) => `| ${row.path} | ${row.sources || "MISSING"} | ${row.license || "MISSING"} | ${row.risk} | ${row.remediation} | ${row.words} |`)
      .join("\n") +
    `\n\n## Category counts\n\n` +
    [...categoryCounts.entries()].sort().map(([category, count]) => `- ${category}: ${count}`).join("\n") +
    "\n";
  await writeFile(path.join(repoRoot, "KB_IP_AUDIT.md"), audit, "utf8");

  const policy = `# KB Content Policy\n\nAs of: ${AS_OF_DATE}\n\nThis knowledge base is built for retrieval-grounded lessons about agentic AI. It stores original synthesized notes, not copied documentation prose.\n\n## Rules\n\n- Use official project documentation first, then the project's own permissively licensed repository, then reputable expert or research sources.\n- Do not copy source prose or code into KB docs. At most one short quote under 25 words is allowed when it is necessary and attributed.\n- Store source text only in ignored raw caches for audit during build; ship only synthesized notes in kb/.\n- Require provenance in frontmatter: title, category, url, license, as_of_date, and sources.\n- Treat unknown, restrictive, GPL/AGPL, source-available, paywalled, or all-rights-reserved sources as facts-only references or skip them.\n- Before embedding replacement, resolve every 🔴 audit item and manually review every 🟠 item.\n- Date-stamp version-sensitive model, pricing, and API guidance.\n\n## Attribution\n\nKB docs cite source URLs in frontmatter and Key links. Citations are provenance, not permission to copy expression.\n`;
  await writeFile(path.join(repoRoot, "KB_CONTENT_POLICY.md"), policy, "utf8");
  const skipped = await writeSkippedLog();

  const red = auditRows.filter((row) => row.risk.startsWith("🔴")).length;
  const orange = auditRows.filter((row) => row.risk.startsWith("🟠")).length;
  console.log(JSON.stringify({ docs: docs.length, red, orange, skipped, manifest: "kb/manifest.yaml", audit: "KB_IP_AUDIT.md" }, null, 2));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
