/** Gemini media orchestration. Keys and raw generated bytes stay server-side. */
import { mediaUrl, saveMedia } from "./media";
import { generateGeminiImage, generateGeminiVideo, type GeneratedMedia } from "./gemini-media";

export type Provider = "gemini" | "off";
export function provider(): Provider { return process.env.GEMINI_API_KEY?.trim() ? "gemini" : "off"; }
export type ImageShape = "hero" | "wide" | "square" | "portrait";
const SHAPES: Record<ImageShape, string> = { hero: "16:9", wide: "16:9", square: "1:1", portrait: "3:4" };
export function lookProPrompt(category: string): string {
  return ["boutique", "retail", "store", "shop"].includes(category)
    ? "Photograph this exact product with a clean neutral studio background, soft lighting and natural shadow. Preserve the product and its details."
    : "Improve lighting and clarity of this exact business photograph. Preserve its scene, people and contents.";
}
async function persist(result: GeneratedMedia): Promise<string> { return mediaUrl(await saveMedia(result.bytes, result.mime)); }

// Retained public URL argument preserves the app contract; Gemini gets inline bytes.
export async function polishImage(imageDataUri: string, _imagePublicUrl: string, category: string): Promise<string | null> {
  if (provider() === "off") return null;
  try { return await persist(await generateGeminiImage(lookProPrompt(category), "1:1", imageDataUri)); }
  catch { console.error("[mediaai] Image enhancement was unavailable"); return null; }
}
export async function generateImage(prompt: string, shape: ImageShape = "square"): Promise<string | null> {
  if (provider() === "off") return null;
  try { return await persist(await generateGeminiImage(prompt, SHAPES[shape])); }
  catch { console.error("[mediaai] Image generation was unavailable"); return null; }
}
export async function generateImagePost(imageDataUri: string, _imagePublicUrl: string, prompt: string): Promise<string> {
  return persist(await generateGeminiImage(prompt, "9:16", imageDataUri));
}
export async function generateReel(imageDataUri: string, _imagePublicUrl: string, prompt: string): Promise<string> {
  return persist(await generateGeminiVideo(prompt, imageDataUri));
}
